version: '3.5'

services:
  app:
    container_name: frontend-stag
    image: frontend-stag
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:80
    restart: unless-stopped
    pull_policy: always
